Change feed processor options - Added option to configure StartTime
atc-net/atc-cosmos pull request #48
Opened 2023-04-24 13:39 UTC by mariusz-pawlowski

We need to give option to configure StartDateTime.

* to keep backward compatibilitiy, when StartDateTime isn't be defined, then DateTime.Min will be set
* there are some databases where data are not good quality (i.e junk data on DEV), and if we start processing then exceptions are thrown

2023-04-24 13:41 UTC, mariusz-pawlowski commented
@LarsSkovslund  will you take a look on this?

2023-04-26 07:54 UTC, LarsSkovslund requested changes

2023-04-26 08:25 UTC, LarsSkovslund commented on src/Atc.Cosmos/ChangeFeedProcessorOptions.cs
> +        public DateTime StartTime { get; set; } = DateTime.MinValue.ToUniversalTime();
Would you also please change the property name from `StartTime` to `DefaultStartTime`

2023-04-26 08:27 UTC, mariusz-pawlowski commented on src/Atc.Cosmos/ChangeFeedProcessorOptions.cs
> +        public DateTime? StartTime { get; set; }
Fix has been done - I've moved Default value to ChangeFeedProcessorOptions.StartTime definition.
Property description (summary) was inspired with official azure cosmos sdk documentation so is this time good enough?

2023-04-26 08:31 UTC, LarsSkovslund commented on src/Atc.Cosmos/ChangeFeedProcessorOptions.cs
> +        public DateTime? StartTime { get; set; }
You are right, lets not confuse existing users of Cosmos SDK by using another name.

2023-04-26 08:32 UTC, merged